#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
from skelpy.arg_parser import ArgParser

def main():
	parser = ArgParser(sys.argv)
	parser.parse()
	parser.exec_cmd()
	return 0

if __name__ == '__main__':
	sys.exit(main())
